# PDF Parser (new) Nexis Texts for Single Files

#### This script is useful for Nexis downloads where all articles are in a single file

In [ ]:
import os
import re
import fitz  # PyMuPDF
import pytesseract
import pandas as pd
from datetime import datetime
from PIL import Image
import PyPDF2

folder_path = r"path_to_your_pdf_folder" #set location of file 
output_csv = "extracted_data.csv" #set name of output file
outlet = "Example News Outlet" # set outlet name

In [3]:
# Check if folder is accessible
print("Exists:", os.path.exists(folder_path))
print("Is Directory:", os.path.isdir(folder_path))

# List first few files
try:
    files = os.listdir(folder_path)
    print(f"Total files detected: {len(files)}")
    print("First 10 files:", files[:10])
except Exception as e:
    print(f"Error listing files: {e}")

pdf_files = [f for f in os.listdir(folder_path) if f.endswith(('.pdf', '.PDF'))]

print(f"Total PDFs found after fix: {len(pdf_files)}")
print("First 10 PDFs:", pdf_files[:10])

Exists: True
Is Directory: True
Total files detected: 11
First 10 files: ['2015.PDF', '2016.PDF', '2017.PDF', '2018.PDF', '2019.PDF', '2020.PDF', '2021.PDF', '2022.PDF', '2023.PDF', '2024.PDF']
Total PDFs found after fix: 11
First 10 PDFs: ['2015.PDF', '2016.PDF', '2017.PDF', '2018.PDF', '2019.PDF', '2020.PDF', '2021.PDF', '2022.PDF', '2023.PDF', '2024.PDF']

In [4]:
#function to parse articles starting at a specific page in the pdf - in single file PDF including multipe articles from Nexis, that page 20 but double check per 
# outlet and adjust accordingly
def extract_articles_from_pdf(pdf_path, start_page=0):
    """Extract articles starting from the given page in the PDF file."""
    articles = []
    with fitz.open(pdf_path) as doc:
        for page_num in range(start_page, len(doc)):
            page_text = doc[page_num].get_text()
            if "Body" in page_text:  #check if the page contains an article
                articles.append(page_text)
    return articles

# Display first article for verification
for filename in os.listdir(folder_path):
    if filename.endswith(('.pdf', '.PDF')):
        pdf_path = os.path.join(folder_path, filename)
        print(f"Processing file: {pdf_path}")
        text = extract_articles_from_pdf(pdf_path)
        print(text[0][:500])  # Print first 500 characters of the first article
    else:
        print(f"Skipping non-PDF file: {filename}")

Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2015.PDF
Page 1 of 2
Chatbot Emma glimlacht na een compliment
Chatbot Emma glimlacht na een compliment
Het Parool
23 oktober 2015 vrijdag
Copyright 2015 De Persgroep Nederland BV All Rights Reserved
Section: Economie; Blz. 17
Length: 336 words
Byline: BART VAN ZOELEN
Body
'Dag Denise, hoe oud ben jij?" vragen we Denise van de Nederlandse Energiemaatschappij (NLE). "Vrouwen
praten niet graag over hun leeftijd en ik ben daar geen uitzondering op," antwoordt ze gevat.
Vijf procent van de vragen aan virtue
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2016.PDF
Page 1 of 3
Groetjes van Anne van Zalando
Groetjes van Anne van Zalando
Het Parool
27 augustus 2016 zaterdag
Copyright 2016 De Persgroep Nederland BV All Rights Reserved
Section: PS Adam; Blz. 50, 51
Length: 1273 words
Byline: ANOUK VLEUGELS
Highlight: In je inbox vechten Anne van Zalando, Sophie van Wehkamp en Billie van Bol om aandacht. Merken die
communiceren als mensen, werkt dat? 'Ze gaan voor het buurmeisjegevoel.'
Body
"Hoi Nikki. Nieuwsgierig als ik ben, hoor ik graag of je mijn kerstca
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2017.PDF
Page 1 of 2
Aldus
Aldus
Het Parool
21 september 2017 donderdag
Copyright 2017 De Persgroep Nederland BV All Rights Reserved
Section: PS Donderdag; Blz. 29
Length: 242 words
Byline: ANDRÉ NIENTIED
Highlight: Amsterdam heeft sinds kort de eerste culturele chatbot, Goochem. Nico Mulder (36), van Amsterdam
Marketing, legt uit.
Body
Goochem gidst je via Facebook Messenger door het culturele aanbod. Hoe werkt het?
"Veel publiek dat gebruikmaakt van het culturele aanbod zit ook op sociale media. Daaro
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2018.PDF
Page 1 of 2
Wat willen we met het algoritme?
Wat willen we met het algoritme?
Het Parool
28 april 2018 zaterdag
Copyright 2018 De Persgroep Nederland BV All Rights Reserved
Section: Wetenschap; Blz. 58
Length: 475 words
Body
GEERT TEN DAM
Stel dat een computer zou bepalen welke onderzoeker de meeste subsidies krijgt. Op basis van data over
succesvol gebleken wetenschappers - leeftijd, sekse, soort onderzoek, enzovoorts - wordt een profiel gemaakt van
'de ideale onderzoeker', waarna een algorit
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2019.PDF
Page 1 of 2
Het moet anders, of de ggz loopt vast
Het moet anders, of de ggz loopt vast
Het Parool
8 augustus 2019 donderdag
Copyright 2019 De Persgroep Nederland BV All Rights Reserved
Section: Nieuws; Blz. 7
Length: 499 words
Byline: RIANNE OOSTEROM
Body
Volgens adviesbureau KPMG kan de ggz niet op de huidige voet verder. In een nieuw rapport wordt gepleit voor
innovaties.
De houdbaarheid van de zorg voor mensen met psychische problemen staat onder druk, schrijft KPMG in het
rapport, dat va
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2020.PDF
Page 1 of 3
'AI kan ons veel leren over onszelf'
'AI kan ons veel leren over onszelf'
Het Parool
15 februari 2020 zaterdag
Copyright 2020 DPG Media B.V. All Rights Reserved
Section: Wetenschap; Blz. 66, 67
Length: 1009 words
Byline: JOSTA BOSMA EN JIM JANSEN
Highlight: Kunstmatig intelligentie behandelt de ene groep mensen anders dan de andere. De computer
discrimineert, heet het dan. Maar eigenlijk is zo'n programma alleen maar een spiegel van onze samenleving, zegt
neuroinformaticus Sennay G
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2021.PDF
Page 1 of 2
Kort nieuws wetenschap
Kort nieuws wetenschap
Het Parool
9 januari 2021 zaterdag
Copyright 2021 DPG Media B.V. All Rights Reserved
Section: Wetenschap; Blz. 58
Length: 335 words
Body
Levantijnen aten eerder Aziatisch voedsel
Mensen in het Middellandse Zeegebied aten duizenden jaren eerder Aziatisch voedsel dan tot nu werd
aangenomen. Dat blijkt uit Duits onderzoek naar microscopisch kleine voedselresten in de opgegraven gebitten van
zestien individuen uit de Levant, aan de oostzijd
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2022.PDF
Page 1 of 3
Vooruitdenken over AI is een morele plicht
Vooruitdenken over AI is een morele plicht
Het Parool
8 december 2022 donderdag
Copyright 2022 DPG Media B.V. All Rights Reserved
Section: Het hoogste woord; Blz. 22
Length: 794 words
Highlight: Computerprogramma's die opinieartikelen schrijven en kunst maken, leken altijd sciencefiction. Het punt
nadert dat software als een mens kan redeneren en beïnvloeden. Tijd om dat gevaar onder ogen te zien, vinden
Otto Barten en Eefje van Esch.
Body
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2023.PDF
Page 1 of 3
We moeten de risico's van AI snel inperken
We moeten de risico's van AI snel inperken
Het Parool
5 mei 2023 vrijdag
Copyright 2023 DPG Media B.V. All Rights Reserved
Section: Het hoogste woord; Blz. 22
Length: 678 words
Byline: OTTO BARTEN
Highlight: Veel experts waarschuwen dat kunstmatige intelligentie (AI) oncontroleerbare vormen kan aannemen,
stelt Otto Barten. Wanneer schakelen we door naar voorkomen in plaats van genezen?
Body
Kunstmatige intelligentie: Actie nodig van politic
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2024.PDF
Page 1 of 3
'Gebruikers van beautyapps zijn dader én slachtoffer'
'Gebruikers van beautyapps zijn dader én slachtoffer'
Het Parool
19 december 2024 donderdag
Copyright 2024 DPG Media B.V. All Rights Reserved
Section: Kunst en Media; Blz. 16
Length: 955 words
Byline: EDO DIJKSTERHUIS
Highlight: De schoonheidsindustrie zadelt vrouwen op met een onrealistisch ideaalbeeld. Kunstenaar Sarah
Amrani laat in Terror of Beauty zien hoe AI daar een schepje bovenop doet.
Body
Foam :Tentoonstelling over AI
Processing file: C:\Users\joly-\OneDrive - Universiteit Utrecht\UU\Dataschool\HUMAN\Data\news\Parool\2025.PDF
Page 1 of 2
Oproep waakhond: 'Kom in actie tegen AI-model Meta'
Oproep waakhond: 'Kom in actie tegen AI-model Meta'
Het Parool
25 april 2025 vrijdag
Copyright 2025 DPG Media B.V. All Rights Reserved
Section: Nieuws; Blz. 11
Length: 608 words
Byline: MAARTJE HUIJBEN EN SEBASTIAAN QUEKEL
Highlight: Wie zijn vakantiekiekjes, selfies of grappige reacties liever niet terugziet in een slim AI-model van Meta,
moet nu in actie komen, waarschuwde Autoriteit Persoonsgegevens (AP) gisteren in een uitzonde

In [5]:
dutch_to_english_months = {
    "januari": "January", "februari": "February", "maart": "March", "april": "April",
    "mei": "May", "juni": "June", "juli": "July", "augustus": "August",
    "september": "September", "oktober": "October", "november": "November", "december": "December"
}

In [6]:
def replace_dutch_months(date_string):
    """Replace Dutch month names with English equivalents."""
    for dutch, english in dutch_to_english_months.items():
        if dutch in date_string.lower():
            return date_string.lower().replace(dutch, english)
    return date_string

def clean_text(text):
    """Clean unwanted characters from text."""
    text = text.replace('\xa0', ' ')
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def find_date_in_text(text):
    """Find and extract date from the entire text, ignoring time information."""
    date_patterns = [
        re.compile(r'(\d{1,2})\s+(januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december)\s+(\d{4})', re.IGNORECASE),
        re.compile(r'(\d{1,2})\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{4})', re.IGNORECASE),
        re.compile(r'(\d{1,2})[-/](\d{1,2})[-/](\d{4})'),
        re.compile(r'(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}', re.IGNORECASE),
    ]
    
    text = clean_text(text)
    for pattern in date_patterns:
        match = pattern.search(text)
        if match:
            return match.group().strip()
    return None

def find_authors(lines):
    """
    Extract authors from the text, assuming they appear in lines starting with 'Byline:'.
    """
    for line in lines:
        if line.startswith("Byline:"):
            # Remove "Byline:" and return the remaining string
            return line.replace("Byline:", "").strip()
    return "Unknown Authors"  # Default if no byline is found

def parse_date(date_string):
    """Parse a date string into a datetime object."""
    if date_string:
        date_string = replace_dutch_months(date_string)
        date_formats = ["%d %B %Y", "%d-%m-%Y", "%d/%m/%Y", "%B %d, %Y"]
        for date_format in date_formats:
            try:
                return datetime.strptime(date_string, date_format)
            except ValueError:
                continue
    return None

def find_title_and_outlet(lines):
    """
    Extract the actual headline from the text, then clean it by removing 'Het Financieele Dagblad'.
    """
    print("DEBUG: First few lines of the text:")
    print(lines[:10])

    headline = lines[1].strip() if len(lines) > 1 else "Unknown Title"
    if len(lines) > 2 and lines[2].strip():
        headline += f" {lines[2].strip()}"

    headline = headline.replace(outlet, "").strip()
    return headline, outlet

def parse_pdf_text(text):
    """Parse the text to extract title, outlet, date, authors, and body."""
    lines = text.split('\n')
    title, outlet = find_title_and_outlet(lines)
    date_string = find_date_in_text(text)
    date = parse_date(date_string) if date_string else None
    authors = find_authors(lines)

    body_start_idx = text.find("Body") + len("Body")
    body_end_idx = text.find("Graphic", body_start_idx)
    body_end_idx = text.find("Classification", body_start_idx) if body_end_idx == -1 else body_end_idx
    body_end_idx = len(text) if body_end_idx == -1 else body_end_idx
    body = text[body_start_idx:body_end_idx].strip()

    return title, outlet, date, authors, body

def parse_pdfs_in_folder(folder_path):
    """Parse all PDFs in a folder, skipping unwanted files, and create a DataFrame."""
    data = []
    missing_dates = []
    skip_files = {""}  # Set of filenames to skip

    for filename in os.listdir(folder_path):
        if filename.endswith(('.pdf', '.PDF')) and filename not in skip_files:
            path = os.path.join(folder_path, filename)
            articles = extract_articles_from_pdf(path)
            for text in articles:
                title, outlet, date, authors, body = parse_pdf_text(text)
                data.append({'title': title, 'outlet': outlet, 'date': date, 'authors': authors, 'body': body})

            if not date:
                missing_dates.append(filename)

    print(f"PDFs missing dates: {missing_dates}")
    return pd.DataFrame(data)


df = parse_pdfs_in_folder(folder_path)

print(df.head())
print(df.shape)

nats_or_nans = df.isna().any(axis=1)
rows_with_nats_or_nans = df[nats_or_nans]

print("Rows with missing values:")
print(rows_with_nats_or_nans.shape)

df_cleaned = df.dropna()
print("Cleaned DataFrame shape:")
print(df_cleaned.shape)

df_cleaned

DEBUG: First few lines of the text:
['Page 1 of 2', 'Chatbot Emma glimlacht na een compliment', 'Chatbot Emma glimlacht na een compliment', 'Het Parool', '23 oktober 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Economie; Blz. 17', 'Length: 336 words', 'Byline: BART VAN ZOELEN', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Vera en Roos hebben het druk', 'Vera en Roos hebben het druk', 'Het Parool', '23 oktober 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Economie; Blz. 17', 'Length: 1135 words', 'Byline: BART VAN ZOELEN', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Mobiel helpt bij praten over eten', 'Mobiel helpt bij praten over eten', 'Het Parool', '3 oktober 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Wetenschap; Blz. 38', 'Length: 622 words', 'Byline: ELLEN SCHLEBUSCH', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Een echte slimme stad is eenspeelse stad', 'Een echte slimme stad is eenspeelse stad', 'Het Parool', '30 mei 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord', 'Length: 885 words', 'Body', 'Smart city: Technocratische benadering omzeilt politiek bij ingrijpende beslissingen ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Spinoza Lyceum populairst', 'Spinoza Lyceum populairst', 'Het Parool', '9 juli 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 2', 'Length: 441 words', 'Byline: LORIANNE VAN GELDER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Leer van big data-incidenten', 'Leer van big data-incidenten', 'Het Parool', '3 januari 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord', 'Length: 780 words', 'Body', 'Keerpunt: De doorbraak van big data ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Brieven', 'Brieven', 'Het Parool', '3 september 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord', 'Length: 469 words', 'Body', 'Geen vrije keuze ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'In nieuwe Albert Heijn is caissière overbodig', 'In nieuwe Albert Heijn is caissière overbodig', 'Het Parool', '6 oktober 2015 dinsdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws', 'Length: 592 words', 'Byline: HERMAN STIL', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Het eerlijke verhaal', 'Het eerlijke verhaal', 'Het Parool', '12 oktober 2015 maandag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord; Blz. 27', 'Length: 480 words', 'Byline: LORIANNE VAN GELDER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', "'Schoolmatching ging goed'", "'Schoolmatching ging goed'", 'Het Parool', '28 augustus 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Amsterdam; Blz. 13', 'Length: 259 words', 'Byline: ROB ROMBOUTS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', 'Stad van stenen en pixels', 'Stad van stenen en pixels', 'Het Parool', '19 mei 2015 dinsdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Dinsdag; Blz. 5', 'Length: 1436 words', 'Byline: TRACY METZ', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Tennisclub IJburg', 'Tennisclub IJburg', 'Het Parool', '16 oktober 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Vrijdag; Blz. 9', 'Length: 633 words', 'Byline: RONALD HOOFT', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', "'Internet maakt ons tot digitalewerkmieren'", "'Internet maakt ons tot digitalewerkmieren'", 'Het Parool', '7 maart 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord', 'Length: 1190 words', 'Byline: MARJOLIJN DE COCQ', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Privacyschending', 'Privacyschending', 'Het Parool', '29 oktober 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Donderdag; Blz. 7', 'Length: 419 words', 'Byline: HANS VAN DER BEEK', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Terugkeer van lotingsysteem: verzet ouders', 'Terugkeer van lotingsysteem: verzet ouders', 'Het Parool', '4 november 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 5', 'Length: 392 words', 'Byline: LORIANNE VAN GELDER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Vincent Reinders', 'Vincent Reinders', 'Het Parool', '18 juli 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS van de week; Blz. 9', 'Length: 607 words', 'Byline: TEKST LISA PETERS FOTOGRAFIE EVA PLEVIER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Gedurfd eten heeft de toekomst', 'Gedurfd eten heeft de toekomst', 'Het Parool', '9 mei 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Wetenschap; Blz. 36', 'Length: 894 words', 'Byline: PETER DE JAEGER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Marktverstoring wordt nog groter', 'Marktverstoring wordt nog groter', 'Het Parool', '7 februari 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord; Blz. 43', 'Length: 712 words', 'Byline: JAN-HENK BOUMAN', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Strijden voor het verzet bij Boom Chicago', 'Strijden voor het verzet bij Boom Chicago', 'Het Parool', '7 november 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Amsterdam; Blz. 21', 'Length: 513 words', 'Byline: MAARTEN VAN DUN', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', "'Luchtmacht werkt straks met satelliet'", "'Luchtmacht werkt straks met satelliet'", 'Het Parool', '3 juli 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 7', 'Length: 859 words', 'Byline: PETER GROENENDIJK', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 5', 'Stream eens wat anders', 'Stream eens wat anders', 'Het Parool', '27 mei 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Woensdag', 'Length: 1397 words', 'Byline: ANOUK VLEUGELS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Matching sterft voortijdige dood', 'Matching sterft voortijdige dood', 'Het Parool', '30 oktober 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Voorpagina; Blz. 1', 'Length: 555 words', 'Byline: LORIANNE VAN GELDER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Dansen tegen de gevel van een bank', 'Dansen tegen de gevel van een bank', 'Het Parool', '24 december 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media; Blz. 36', 'Length: 459 words', 'Byline: JAN PIETER EKKER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', 'Hard schreeuwen loont', 'Hard schreeuwen loont', 'Het Parool', '12 november 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws', 'Length: 1493 words', 'Byline: TEKST LORIANNE VAN GELDER ILLUSTRATIE TED STRUWER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', 'DE WERELD SHAZAMMEN', 'DE WERELD SHAZAMMEN', 'Het Parool', '25 maart 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Woensdag', 'Length: 1222 words', 'Byline: ANOUK VLEUGELS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Sneeuw uit de speakers', 'Sneeuw uit de speakers', 'Het Parool', '14 december 2015 maandag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Maandag', 'Length: 1034 words', 'Byline: LEX BOON', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Minder scholieren op hun favoriete school', 'Minder scholieren op hun favoriete school', 'Het Parool', '5 juni 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 11', 'Length: 637 words', 'Byline: LORIANNE VAN GELDER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Constant klikken op echte hotspots', 'Constant klikken op echte hotspots', 'Het Parool', '27 juni 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 9', 'Length: 687 words', 'Byline: THOM EGBERTS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', "'Klassiek heeft geen fish & chips-gevoel'", "'Klassiek heeft geen fish & chips-gevoel'", 'Het Parool', '17 oktober 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws', 'Length: 1528 words', "Byline: TEKST MARJOLIJN DE COCQ FOTO'S HARMEN DE JONG", 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', 'Jagen op de generatie slim en snel', 'Jagen op de generatie slim en snel', 'Het Parool', '4 februari 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws', 'Length: 1275 words', 'Byline: BART VAN ZOELEN', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 1', 'Spotcap: mkb kan snel geld lenen', 'Spotcap: mkb kan snel geld lenen', 'Het Parool', '6 maart 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Economie; Blz. 16', 'Length: 139 words', 'Byline: EVA GABELER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', "Graag een date, niet zo'n creep", "Graag een date, niet zo'n creep", 'Het Parool', '22 juli 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Woensdag', 'Length: 1116 words', 'Byline: TEKST ANOUK VLEUGELS FOTO SHUTTERSTOCK', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Ineens 1,5 miljard waard', 'Ineens 1,5 miljard waard', 'Het Parool', '17 juli 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Vrijdag', 'Length: 1290 words', 'Byline: JOEP SCHOOL', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Harde jongens, die copycat-broers', 'Harde jongens, die copycat-broers', 'Het Parool', '6 maart 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Economie; Blz. 16', 'Length: 842 words', 'Byline: EVA GABELER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Een computer met een mensenbrein', 'Een computer met een mensenbrein', 'Het Parool', '10 januari 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Wetenschap; Blz. 42', 'Length: 774 words', 'Byline: TEKST YANNICK FRITSCHY ILLUSTRATIE JEROEN MURRE', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Spraakherkenning gaat erg ver', 'Spraakherkenning gaat erg ver', 'Het Parool', '11 februari 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 9', 'Length: 503 words', 'Byline: PEET VOGELS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'De toekomst begint nu', 'De toekomst begint nu', 'Het Parool', '12 mei 2015 dinsdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord; Blz. 23', 'Length: 483 words', 'Byline: KARIN SPAINK', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Autonoom, precies en dodelijk', 'Autonoom, precies en dodelijk', 'Het Parool', '1 augustus 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord; Blz. 35', 'Length: 581 words', 'Byline: ADDIE SCHULTE', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', '[Kort nieuws Economie Alibaba neemt Chinese YouTube ...]*', '[Kort nieuws Economie Alibaba neemt Chinese YouTube...]*', 'Het Parool', '7 november 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Economie', 'Length: 332 words', 'Byline: ANP', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Een robot die politieman, mens noch gangster kan zijn', 'Een robot die politieman, mens noch gangster kan zijn', 'Het Parool', '4 maart 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Woensdag; Blz. 13', 'Length: 373 words', 'Byline: BART VAN DER PUT', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Ook Kennedy kwam bij Madame Claude', 'Ook Kennedy kwam bij Madame Claude', 'Het Parool', '23 december 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Buitenland; Blz. 15', 'Length: 322 words', 'Byline: ANP', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', 'Tussen mens en machine', 'Tussen mens en machine', 'Het Parool', '8 april 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Woensdag', 'Length: 1240 words', 'Byline: BART VAN DER PUT', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Verzin alternatief voor de toekomst', 'Verzin alternatief voor de toekomst', 'Het Parool', '21 mei 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Het Laatste Woord; Blz. 23', 'Length: 589 words', 'Body', "In een wereld waarin op één vacature honderden brieven en cv's binnenkomen, regeert het bedrijfsleven. In zo'n "]
DEBUG: First few lines of the text:
['Page 1 of 2', 'Dit rook Kadhafi toen hij stierf', 'Dit rook Kadhafi toen hij stierf', 'Het Parool', '28 november 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 5', 'Length: 589 words', 'Byline: JAN PIETER EKKER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Praatpalen die ruzie kunnen maken', 'Praatpalen die ruzie kunnen maken', 'Het Parool', '12 december 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Wetenschap; Blz. 37', 'Length: 700 words', 'Byline: SEBASTIAAN VAN DE WATER', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Avatar als buddy', 'Avatar als buddy', 'Het Parool', '7 januari 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Woensdag; Blz. 6', 'Length: 890 words', 'Byline: MARIANNE EGGINK', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Ai Weiwei heeft paspoort terug', 'Ai Weiwei heeft paspoort terug', 'Het Parool', '23 juli 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media; Blz. 19', 'Length: 298 words', 'Body', 'HONG KONG - De Chinese kunstenaar en activist Ai Weiwei (57) heeft weer een paspoort. De pas van de artiest ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Ai Caramba', 'Ai Caramba', 'Het Parool', '29 oktober 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Donderdag; Blz. 17', 'Length: 531 words', 'Byline: SAMUEL LEVIE', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 4', 'Waar Larsson ophield', 'Waar Larsson ophield', 'Het Parool', '10 september 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Donderdag', 'Length: 1274 words', 'Byline: MAARTEN MOLL', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Het tragische leven van de unieke Vivier', 'Het tragische leven van de unieke Vivier', 'Het Parool', '3 augustus 2015 maandag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media; Blz. 14', 'Length: 933 words', 'Byline: ERIK VOERMANS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Oprecht en overtuigend strijdbaar', 'Oprecht en overtuigend strijdbaar', 'Het Parool', '18 juni 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: PS Donderdag; Blz. 10', 'Length: 242 words', 'Byline: JERRY GOOSSENS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Een land op slot', 'Een land op slot', 'Het Parool', '25 juli 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Buitenland; Blz. 13', 'Length: 446 words', 'Byline: FRANK RENOUT', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'kort nieuws kunst', 'kort nieuws kunst', 'Het Parool', '5 februari 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media', 'Length: 312 words', 'Body', 'Thomas Acda gaat telefilm regisseren ']
DEBUG: First few lines of the text:
['Page 1 of 3', 'Pirouettes draaien in de ruimte', 'Pirouettes draaien in de ruimte', 'Het Parool', '27 juni 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Wetenschap; Blz. 38', 'Length: 878 words', 'Byline: PETER DE BROCK', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'kort nieuws kunst', 'kort nieuws kunst', 'Het Parool', '26 maart 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media; Blz. 19', 'Length: 254 words', 'Body', 'Hans Sibbel komend seizoen weer theater in ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'kort nieuws kunst en media', 'kort nieuws kunst en media', 'Het Parool', '20 juni 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media', 'Length: 311 words', 'Body', 'Split van Jean-Claude Van Damme vereeuwigd ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'kort nieuws kunst', 'kort nieuws kunst', 'Het Parool', '10 oktober 2015 zaterdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media', 'Length: 329 words', 'Body', 'Radio 6 Awards voor Giovanca en Bo Saris ']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Een verbijsterend productieve bard', 'Een verbijsterend productieve bard', 'Het Parool', '30 januari 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Kunst En Media; Blz. 19', 'Length: 181 words', 'Byline: ERIK VOERMANS', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Kamer wil geld voor kleine ziekenhuizen', 'Kamer wil geld voor kleine ziekenhuizen', 'Het Parool', '26 mei 2015 dinsdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws', 'Length: 453 words', 'Byline: FRANCINE WILDENBORG', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Voor altijd de man van Probo Koala', 'Voor altijd de man van Probo Koala', 'Het Parool', '2 oktober 2015 vrijdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Economie; Blz. 17', 'Length: 403 words', 'Byline: HERMAN STIL', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', "'Nederlandse belastingtruc benadeelt Grieken'", "'Nederlandse belastingtruc benadeelt Grieken'", 'Het Parool', '2 september 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 7', 'Length: 425 words', 'Byline: FRANS BOOGAARD', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Kritiek op houding Orbán', 'Kritiek op houding Orbán', 'Het Parool', '9 september 2015 woensdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Nieuws; Blz. 5', 'Length: 475 words', 'Byline: CHRISTOPH SCHMIDT', 'Body']
DEBUG: First few lines of the text:
['Page 1 of 2', 'Vloekend naar de meet', 'Vloekend naar de meet', 'Het Parool', '19 februari 2015 donderdag', 'Copyright 2015 De Persgroep Nederland BV All Rights Reserved', 'Section: Sport; Blz. 21', 'Length: 433 words', 'Byline: THIJS ZONNEVELD', 'Body']
DEBUG: First few lines of the text:

,title,outlet,date,authors,body
0,Chatbot Emma glimlacht na een compliment Chatb...,Parool,2015-10-23,BART VAN ZOELEN,"'Dag Denise, hoe oud ben jij?"" vragen we Denis..."
1,Vera en Roos hebben het druk Vera en Roos hebb...,Parool,2015-10-23,BART VAN ZOELEN,Klantenservice: Virtuele medewerkers kunnen st...
2,Mobiel helpt bij praten over eten Mobiel helpt...,Parool,2015-10-03,ELLEN SCHLEBUSCH,Voedseldialoog: Wageningen UR brengt app met e...
3,Een echte slimme stad is eenspeelse stad Een e...,Parool,2015-05-30,Unknown Authors,Smart city: Technocratische benadering omzeilt...
4,Spinoza Lyceum populairst Spinoza Lyceum popul...,Parool,2015-07-09,LORIANNE VAN GELDER,AMSTERDAM - De populairste scholen van de stad...
...,...,...,...,...,...
2301,Bij nieuwe pandemie staat niemand paraat Bij n...,Parool,2025-03-01,JOP VAN KEMPEN EN BAS SOETENHORST,Vijf jaar later: Nederland is nu slechter voor...
2302,De Rolls-Royce onder de naaimachines De Rolls-...,Parool,2025-02-01,MARLOES DE MOOR,"""Je uploadt een fotootje en maakt er in twee t..."
2303,'De Tweede Wereldoorlog is nog niet met pensio...,Parool,2025-05-03,BJARN VAN DEN BERG,'Weet U het nog? U wel - maar ook het nageslac...
2304,'Niets in mijn jeugd heeft me voorbereid op he...,Parool,2025-03-08,MARCEL WIEGMAN,"""Het is gek,"" zegt Martin Rombouts. ""Ik was al..."
2305,'Niets in mijn jeugd heeft me voorbereid op he...,Parool,2025-03-08,MARCEL WIEGMAN,"""Het is gek,"" zegt Martin Rombouts. ""Ik was al..."

In [7]:
# Calculate word count for each row in the 'body' column
df_cleaned['word_count'] =df_cleaned['body'].apply(lambda x: len(str(x).split()))

# Display the DataFrame with the new 'word_count' column
df_cleaned.head()

C:\Users\joly-\AppData\Local\Temp\ipykernel_11988\614310843.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['word_count'] =df_cleaned['body'].apply(lambda x: len(str(x).split()))

,title,outlet,date,authors,body,word_count
0,Chatbot Emma glimlacht na een compliment Chatb...,Parool,2015-10-23,BART VAN ZOELEN,"'Dag Denise, hoe oud ben jij?"" vragen we Denis...",238
1,Vera en Roos hebben het druk Vera en Roos hebb...,Parool,2015-10-23,BART VAN ZOELEN,Klantenservice: Virtuele medewerkers kunnen st...,249
2,Mobiel helpt bij praten over eten Mobiel helpt...,Parool,2015-10-03,ELLEN SCHLEBUSCH,Voedseldialoog: Wageningen UR brengt app met e...,288
3,Een echte slimme stad is eenspeelse stad Een e...,Parool,2015-05-30,Unknown Authors,Smart city: Technocratische benadering omzeilt...,270
4,Spinoza Lyceum populairst Spinoza Lyceum popul...,Parool,2015-07-09,LORIANNE VAN GELDER,AMSTERDAM - De populairste scholen van de stad...,210

In [8]:
df_cleaned.shape

(2298, 6)

In [9]:
# Ensure 'date' is treated as string before regex
df['date'] = df['date'].apply(
    lambda x: str(x) + " 00:00:00" if pd.notna(x) and not re.search(r'\d{2}:\d{2}:\d{2}', str(x)) else str(x)
)

# Convert to datetime
df['date'] = pd.to_datetime(df['date'].str.strip(), errors='coerce')

In [10]:
df['year'] = df['date'].dt.year

In [11]:
#check if there are any NaNs in the 'date' column
nan_exists = df['date'].isna().any()
print(f"Are there any NaNs in 'date'? {nan_exists}")

#count exactly how many NaNs there are
nan_count = df['date'].isna().sum()
print(f"Number of NaNs in 'date': {nan_count}")

Are there any NaNs in 'date'? True
Number of NaNs in 'date': 8

In [12]:
counts_per_year = df['year'].value_counts().sort_index()
print(counts_per_year)

year
2015.0    184
2016.0    195
2017.0    192
2018.0    192
2019.0    257
2020.0    139
2021.0    181
2022.0    152
2023.0    265
2024.0    298
2025.0    243
Name: count, dtype: int64

In [16]:
output_folder = os.path.dirname(folder_path)

#save to folder
df_cleaned.to_csv(os.path.join(output_folder, output_csv))